name: Run API Tests

on:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t selenium-java-test ./ApiTests

      - name: Run tests and generate Allure report inside Docker
        run: |
          docker run --rm --user root \
          -v ${{ github.workspace }}/ApiTests/allure-results:/app/target/allure-results \
          -v ${{ github.workspace }}/ApiTests/allure-report:/app/target/site/allure-maven-plugin \
          selenium-java-test mvn test allure:report

      - name: Debug Docker report folder (optional)
        run: |
          ls -l ${{ github.workspace }}/ApiTests/allure-report
          
      - name: Fix permissions and remove existing .git folder
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}/ApiTests/allure-report
          rm -rf ${{ github.workspace }}/ApiTests/allure-report/.git || true
          
      - name: Deploy Allure report to GitHub Pages
        run: |
          cd ${{ github.workspace }}/ApiTests/allure-report
          git init
          git checkout -b gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git add .
          git commit -m "Update Allure Report"
          git push --force origin gh-pages



